//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Development.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Development.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language change will take effect after restarting the application.Do you Reset now.
        /// </summary>
        public static string MS_Change_Language {
            get {
                return ResourceManager.GetString("MS_Change_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PG_MAIN_btHome {
            get {
                return ResourceManager.GetString("PG_MAIN_btHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string PG_MAIN_btReset {
            get {
                return ResourceManager.GetString("PG_MAIN_btReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string PG_MAIN_btStart {
            get {
                return ResourceManager.GetString("PG_MAIN_btStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string PG_MAIN_btStop {
            get {
                return ResourceManager.GetString("PG_MAIN_btStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Menu.
        /// </summary>
        public static string PG_MN_Assign_Menu {
            get {
                return ResourceManager.GetString("PG_MN_Assign_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string PG_MN_Login {
            get {
                return ResourceManager.GetString("PG_MN_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string PG_MN_LogOut {
            get {
                return ResourceManager.GetString("PG_MN_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Operation.
        /// </summary>
        public static string PG_MN_Manual_Operation {
            get {
                return ResourceManager.GetString("PG_MN_Manual_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical Menu.
        /// </summary>
        public static string PG_MN_Mechanical_Menu {
            get {
                return ResourceManager.GetString("PG_MN_Mechanical_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string PG_MN_Menu_Model {
            get {
                return ResourceManager.GetString("PG_MN_Menu_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Menu.
        /// </summary>
        public static string PG_MN_Status_Menu {
            get {
                return ResourceManager.GetString("PG_MN_Status_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User Menu.
        /// </summary>
        public static string PG_MN_Super_User_Menu {
            get {
                return ResourceManager.GetString("PG_MN_Super_User_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Menu.
        /// </summary>
        public static string PG_MN_System_Menu {
            get {
                return ResourceManager.GetString("PG_MN_System_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Menu.
        /// </summary>
        public static string PG_MN_TeachingMenu {
            get {
                return ResourceManager.GetString("PG_MN_TeachingMenu", resourceCulture);
            }
        }
    }
}
